### ISSUE TITLE
Question regarding conditions

### ISSUE THREAD

**Issue by Foggalong** [alexwlchan/hurley#5]
Do the people have to be hosts or does this include guests also?

**Comment by Cin316** [comment]
@Foggalong From Cortex I got the impression that people have to be hosts, as it was comparing cohosts of different podcasts.

**Comment by alexwlchan** [comment]
Sorry for the late reply @Foggalong; yes, it does just count people who have been regular hosts of a podcast.

**Comment by Foggalong** [comment]
Ah, thanks :) I'll be sure to start adding as many podcasts as I can to this in the near future.
